### PR TITLE
Added LDD

### PR DESCRIPTION
**Pull request by FiF0o**
dockerise, deploy CI/CD, deploy config on travis to heroku, heroku config env var to be added

### CODE REVIEW

**Comment by marcospeebles** [comment]
Sorry Sir, it seems that your PULL request has no conflicts with the base branch. Please amend this as per policy we need at least one conflict in order to accept it. Thanks for helping out though, keep it going

**Comment by marcospeebles** [comment]
After talking to our peer overseas no shore committee we decided to make an exception and accept it.

**Comment by marcospeebles** [comment]
Now there is at least one more step. This could technically classify as a mental bug. Hence merge

**Comment by luciocodeghini** [comment]
no-conflicts

**Pull request merged**
